### ISSUE TITLE
Type parameter constraint of generic function not checked in function expression used as argument

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#273] opened 2016-09-26 16:40 UTC
I tried to solve a problem noted in http://www.typescriptlang.org/docs/handbook/type-compatibility.html#function-parameter-bivariance by introducing type variables.

```
enum EventType { Mouse, Keyboard }

interface Event { timestamp: number; }
interface MouseEvent extends Event { x: number; y: number }
interface KeyEvent extends Event { keyCode: number }

class MouseEventImpl implements MouseEvent{}

function <T extends Event> listenEvent(eventType: EventType, handler: (n: T) => void) {
    if (eventType==EventType.Mouse) {
        handler(new MouseEventImpl() as T); // ugly ugly ugly
    }
    /* ...*/
}

// XPECT noerrors -->
listenEvent(EventType.Mouse, (e: MouseEvent) => console.log(e.x + "," + e.y));

// XPECT errors FIXME --> {function(number):any} is not a subtype of {function(T):void}.
listenEvent(EventType.Mouse, (e: number) => console.log(e));
// XPECT errors FIXME --> {function(number):any} is not a subtype of {function(T):void}.
listenEvent(EventType.Mouse, function(e: number) { console.log(e) } );
// XPECT errors --> {function(number):any} is not a subtype of {function(Event):void}.
<Event>listenEvent(EventType.Mouse, (e: number) => console.log(e));


// XPECT type of 'e' --> Event
listenEvent(EventType.Mouse, (e) => console.log(e));
```

The type parameter has a lower bound Event. This lower lower bound is not checked, as shown in the second call. However, the lower bound is used to correctly infer the type of the parameter to Event, as shown in the third call.

**Comment by JensN4** [comment] 2016-09-26 16:54
I'm aware that this case is a little awkward, and it does not solve any real problem, as the code in listenEven is really ugly.... well...

It would be nice (from the perspective of the implementor of listenEvent) to use type parameters in function type expressions, e.g.

```
function listenEvent2(eventType: EventType, handler: {function <T extends Event> (n: T): void}) {
     if (eventType==EventType.Mouse) {
        handler(new MouseEventImpl());
    }
}

// XPECT errors --> {function(MouseEvent):any} is not a subtype of {function<T extends Event>(T):void}.
listenEvent2(EventType.Mouse, (e: MouseEvent) => console.log(e.x + "," + e.y));

// XPECT errors --> {function(number):any} is not a subtype of {function<T extends Event>(T):void}.
listenEvent2(EventType.Mouse, (e: number) => console.log(e));

// we do not gain much, but at least XPECT noerrors -->
listenEvent2(EventType.Mouse, function<T extends Event>(e: T) { console.log(e) } );
```

but that would make the call side as ugly as in the original TS example.
And I'm pretty sure that the errors are correct, aren't they?

**Comment by mor-n4** [comment] 2016-09-27 06:41
regarding the example from the main issue description:

imo, this is not a bug; the type argument inference works as intended. For the following call expression from the above example

```
listenEvent(EventType.Mouse, (e: number) => console.log(e));
```

the type system will infer the solution `T = Event & number`. This solution is valid, which can be checked by using a call expression with explicitly defined type arguments:

```
// XPECT noerrors -->
<Event & number>listenEvent(EventType.Mouse, (e: number) => console.log(e));
```

One could argue that this is counter intuitive and that the type argument inference should not use "empty intersections" such as `Event & number` as a solution. However, we have a user story for this, see IDE-2302.

I have added the above example (from the main issue description) as an example to IDE-2302.

**Comment by mor-n4** [comment] 2016-09-27 12:53
after discussion with Jens: closing this as duplicate of IDE-2302.

**Closed as completed by mor-n4** 2016-09-27 12:53 UTC
Labels: bug
