### ISSUE TITLE
array destructuring uses `var` when `let` has been specified, causes error

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#216] opened 2016-06-13 09:49 UTC
``` js
function foo() {
    let m = new Map<string, int>();
    m.set("foo", 3);

    let v = 34;
    for (let [k, v] of m) {

    }
}
foo();
```

leads to "Scope.js:199 Uncaught SyntaxError: Identifier 'v' has already been declared".

**Comment by arrowplum** [comment] 2016-06-13 15:59
Dupe of #195

**Comment by arrowplum** [comment] 2016-06-13 16:01
It's not for me to close things. Leaving it open.

**Closed as completed** 2016-06-29 07:57 UTC
Labels: duplicate
