### ISSUE TITLE
Unclear if ClassifierTypeRef may be used for other types than TClassifier (enums, primitive types, type variables)

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#22] opened 2016-03-16 12:44 UTC
IDEBUG-306
 Problem:
- on the one hand, ClassifierTypeRefs can be created for all kinds of types, not just TClassifier (parser allows that and no validation in place to disallow)
- on the other hand, the name ClassifierTypeRef suggests that the 'staticType' property must point to a TClassifier (also the Spec suggests that, without static it explicitly) and it seems that only these cases are supported by now

Either (a) add a validation to disallow non-TClassifier static types OR (b) add support for all other cases and consider renaming ClassifierTypeRef to something more appropriate

In case of (b): investigate whether now EnumTypeRef is still required or if the renamed ClassifierTypeRef could be used for these cases.

Some food for thought:

```
// type variables are currently allowed as static types of ClassifierTypeRefs

class C<T> {
    type{T} field;
}


// built-in types are currently allowed as static types of ClassifierTypeRefs

var type{any} tt;

tt = Color; // raises error (probably wrong)

tt = string; // raises error (probably wrong)

tt = any; // raises error (probably wrong)


class D {}
tt = D; // no error (ok)


// enums are currently allowed as static types of ClassifierTypeRefs

enum Color { RED, GREEN, BLUE }

var type{Color} tcol; // will create a ClassifierTypeRef
var Color col; // will create an EnumTypeRef


tcol = col; // raises error (makes sense, probably)
col = tcol; // raises error (makes sense, probably)

tcol = Color; // no error (why? correct?)
```

Background: created this while working on IDE-1127; first tried to solve it as part of that task, but this needs some more thought --> thus a separate task.

**Comment by mor-n4** [comment] 2016-09-19 14:53
enums and type variables are now solved; see IDE-2320 for remaining problematic cases

**Comment by mor-n4** [comment] 2018-02-07 11:24
Closing as duplicate of IDE-2320.

**Closed as completed by mor-n4** 2018-02-07 11:24 UTC
Labels: bug, duplicate
