### ISSUE TITLE
Wrong warning on @Promisifiable signature regarding await

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#261] opened 2016-09-09 12:24 UTC
##### A.n4js.xt

```
import * as lib_fs from "fs";

async function foo() {
    // XPECT nowarnings
    await lib_fs.readFile("bar.txt", { encoding: "UTF-8" });
}

```

**Comment by mor-n4** [comment] 2016-09-30 14:36
closing this as duplicate of #268

**Closed as completed by mor-n4** 2016-09-30 14:36 UTC
Labels: duplicate
