### ISSUE TITLE
Missing validation for references to primitive types

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#393] opened 2017-05-17 11:19 UTC
##### foo.n4js.xt
```

// XPECT errors --> "string is not known"
const foo = string;

// XPECT errors --> "string is not known"
{
    foo: string
}

// XPECT errors --> "number is not known"
const bar = number;

// ... symbol
```

**Comment by mor-n4** [comment] 2017-05-17 11:31
duplicate of #280 and already fixed
(fix was merged to the new master only, hence it did not land in the product, yet)

**Closed as completed** 2017-05-17 11:31 UTC
Labels: duplicate
