### ISSUE TITLE
Assign object literals to nested, use-side defined, structural type fields

### ISSUE THREAD

**Issue by mmews-n4** [NumberFour/n4js#250] opened 2016-08-11 15:12 UTC
When using object literals to create an structural type object, this new object might have nested fields. In case the nested field is also of structural type, it should also be possible to assign an object literal to it. This is not possible in the situation below.

```
interface A {    public i : int;   }
interface I<T> {    public x : ~T;    }

class     C2   {   
    // ATTENTION return value must be ~I, all well
    // XPECT FIXME noerrors -->
    public f2b () : ~I<A> { return {x: {i: 3} };  }
}
```

Note: search for GH-250 in matrix tests.

**Comment by mmews-n4** [comment] 2016-08-23 11:37
see: https://jira.numberfour.eu/browse/IDEBUG-225
see: https://github.com/NumberFour/n4js/issues/12

**Comment by JensN4** [comment] 2016-08-24 09:08
This is not a bug. The problem is in the last line: `~I<A>` refers to a structural interface I, but to a nominal interface A. Changing that to `~I<~A>` fixes the problem:

```
interface A {    public i : int;   }
interface I<T> {    public x : ~T;    }

class     C2   {   
    // ATTENTION return value must be ~I, all well
    // XPECT FIXME noerrors -->
    public f2b () : ~I<~A> { return {x: {i: 3} };  }
}
```

**Comment by JensN4** [comment] 2016-08-24 09:10
This is a duplicate of #12, isn't it?

**Closed as completed** 2016-08-24 09:24 UTC
Labels: duplicate
