### ISSUE TITLE
Static N4Getters and N4Setters with name "name" result with runtime errors

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#6] opened 2016-03-16 12:44 UTC
IDEBUG-61
 consider N4Class:

```
class A{
    private static string myName = 'foo';
    public static string get name() {
        return this.myName;
    }

    public static set name(string s){
        this.myName = s;
    }

    public static sayMyName(){
        console.log(this.myName);
    }
}
A.sayMyName();
console.log(A.name);
A.name = 'bar';
console.log(A.name);
A.name = 'baz'
A.sayMyName();
```

when running this code output is:

```
Error was: TypeError: Cannot redefine property: name
Load or compilation failure: Review-0.0.1/Name.js
```

This seems load time error.

Notice that it is only the case with static setters and getters. With instance based properties/setters/getters this doesn't happen.
So, for code:

```
class B{
    private string myName = 'foo';
    public string get name() {
        return this.myName;
    }

    public set name(string s){
        this.myName = s;
    }

    public sayMyName(){
        console.log(this.myName);
    }
}
var b = new B();
b.sayMyName();
console.log(b.name);
b.name = 'bar';
console.log(b.name);
b.name = 'baz'
b.sayMyName();
```

we get output:

```
foo
foo
bar
baz
```

"name" is a static property of function constructors:

```
> function A() {};
undefined
> var a = new A();
undefined
> a.constructor.name
'A'
```

Solution: add final flag to members in type system and modify "name" property of function accordingly.

**Comment by mor-n4** [comment] 2018-02-07 13:30
Closing this as CANNOT REPRODUCE.

**Closed as completed by mor-n4** 2018-02-07 13:30 UTC
Labels: bug, wontfix, prio-low
