### ISSUE TITLE
"Run as" on offers "Launch in NodeJS" even if NodeJS does not provide all rt libs

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#136] opened 2016-03-16 18:11 UTC
IDEBUG-460

Even if project that relies on runtime libraries not provided by the node.js environment, e.g. html, in the context run menu, "Launch in NodeJS" is proposed (although it can only be run by a different runtime environment).

**Comment by mor-n4** [comment] 2016-09-20 13:23
Cannot reproduce.

Seems to work as intended with file `Main.n4js` in `eu.numberfour.fabelhaft`.
Seems to work as intended with small example projects in an empty workspace (also if dependency to unsupported runtime library is defined only indirectly through another n4js project).

Closing as "works for me".

**Closed as completed** 2016-09-20 13:24 UTC
Labels: bug
