### ISSUE TITLE
Constructor property vs. type constructor

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#69] opened 2016-03-16 12:52 UTC
IDEBUG-670
 Using the constructor property of an object should behave similar to using the type right away, i.e.
{panel:title=Generated bug report|borderStyle=dashed|borderColor=#ccc|titleBGColor=#8192A6|bgColor=#dedee0}
{{A.n4js.xt}}

```
class C {}
var C c;

var ctor1 = C;
// XPECT nowarnings --> "A reference to method constructor is created detached from a (correct) this-instance."
var ctor2 = c.constructor;

```

{panel}

**Comment by JensN4** [comment] 2016-06-30 10:16
closed, duplicate of #224

**Closed as completed by JensN4** 2016-06-30 10:16 UTC
Labels: duplicate
