### ISSUE TITLE
N4MF, order of "Sources" content (external, sources,...) effects project resolution and may break build.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#15] opened 2016-03-16 12:44 UTC
IDEBUG-240
 Took the Point/Circle example from the IDE-Spec document with a using class, an *n4jsd file and a *js file. 

Iff in the manifest.n4mf the sources are given like

```
Sources {
    external { "ext" }
    source { 
        "src"
    }
}
```

the project will not compile with an error of "Couldn't resolve reference to IdentifiableElement 'Point'."

Presented solution is to import the class the very exact way it is already imported. 

Cause: 
The order has to be sources first, externals last.

We need at least a validation for this and document it in the spec.

A more intuitively solution would be to make the order irrelevant.

**Comment by mor-n4** [comment] 2018-02-07 15:12
Tried to reproduce this, but the order of sources/externals did not have any effect.

Closing as CANNOT REPRODUCE.

**Closed as completed by mor-n4** 2018-02-07 15:12 UTC
Labels: bug, prio-low, movedToEclipse
