### ISSUE TITLE
Content provider issue with working sets

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#101] opened 2016-03-16 12:56 UTC
When the N4JS features are activated in the project explorer, several issues arise, including:
- projects are shown as single projects AND in working sets
- working sets are not shown correctly
- importing projects and adding them automatically to working sets causes the IDE to hang

In general the combination of working sets, N4JS feature and the project explorer seems to cause problems.

Review N4JS feature implementation and fix working set issues.

imported:
IDEBUG-811
This may produce duplicate projects in the explorer.

**Comment by JensN4** [comment] 2016-04-13 09:59
also see #62

**Comment by kittaakos** [comment] 2016-04-25 14:05
> importing projects and adding them automatically to working sets causes the IDE to hang

I was unable to reproduce that part of the task, so closed associated issue #147

**Closed as completed** 2016-05-24 12:21 UTC
Labels: bug, prio-high
