### ISSUE TITLE
#39: Content Assist doesn't reliably work in generator functions

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#325] opened 2017-01-06 08:54 UTC
The following code doesn't content assist the members of `req`:
```js
class A {}
export public function* foo(req: A) { // removing export public fixes the problem 
    yield 5; // removing 5 fixes the problem
    req. // <-- content assist here ctrl+space
}
```

**Comment by JensN4** [comment] 2017-01-09 14:33
Probably a problem with our parameterized rules. In some cases, a wrong method name is generated. This rule name is created with information from the generated (Content Assist) parser, cf. https://github.numberfour.eu/NumberFour/n4js/blob/master/plugins/org.eclipse.n4js.ui/src-gen/org/eclipse/n4js/ui/contentassist/antlr/N4JSParser.java#428
This leads to a non-existing method name: java.lang.NoSuchMethodException: eu.numberfour.n4js.ui.contentassist.CustomN4JSParser$CustomInternalN4JSParser.norm3_AssignmentExpression__Group_3__0()

Solutions:
- fix generated code (Xtext bug)
- avoid usage of parameterized rules by moving the yield/non-yield check to the validator (ASTStructureValidator)

However this may only be a consequential or different error, accidentally revealed by this problem.

**Comment by mmews-n4** [comment] 2017-01-10 08:59
Removing the <Yield> parameter from the grammars solves the initial issue and the issue described above. As a consequence to removing the <Yield> parameter, the `yield` expression is now available everywhere and indicated as an error using succeeding validations.

**Comment by arrowplum** [comment] 2017-04-21 15:37
Is the fix here https://github.com/NumberFour/n4js/issues/325#issuecomment-271520892 in the product? I am still having this issue.

**Comment by arrowplum** [comment] 2017-05-30 09:52
Issue still remains, right?

**Comment by mmews-n4** [comment] 2017-05-31 06:08
I added an issue in the XText project: https://github.com/eclipse/xtext/issues/2585

**Comment by mmews-n4** [comment] 2017-05-31 06:09
Yes, the issue still remains. As of now, we cannot deal with it since it is caused by XText.

**Comment by szarnekow** [comment] 2017-07-10 11:39
Mirrored to https://github.com/eclipse/n4js/issues/39

**Comment by yoosiba** [comment] 2017-07-14 19:28
@mmews-n4 @szarnekow can we close this as per https://github.com/eclipse/n4js/issues/39 ?

**Comment by mmews-n4** [comment] 2017-07-17 05:55
Sure (this repo here is an obsolete copy).

**Closed as completed** 2017-07-17 07:12 UTC
Labels: bug, help wanted, prio-high, toEclipse
