### ISSUE TITLE
Wrong linking in case of Polyfill usage.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#58] opened 2016-03-16 12:52 UTC
IDEBUG-614
 Following situation:
RL-Project P1 defines a Type via definition:

```
// file: P1/src/A.n4jsd
export public class A {}
```

RL-Project P2 polyfills it:

```
// file: P2/src/A.n4jsd
@Polyfill
export public class A extends A { public shinyNewMethod(); }
```

User of type A in a third Project:
Project P3 

```
// file: P3/src/User.n4js
import A from "A";  // A is linked to P1/A.A or P2/A.A depending on order of reference in Manifest. 
var A a = new A();
a.shinyNewMethod(); 
```

Depending on the order of `RequiredRuntimeLibraries { P2,P1 }` in `P3/manifest.n4mf` the usage of A gets linked to either the Filled (P1/A) or the Filling (P2/A) module/type.

It should always link to the filled type.

**Comment by mor-n4** [comment] 2016-09-26 15:03
tried the example from the issue description and various other scenarios but it always behaves as expected.

closing this as "can't reproduce" (seems this was fixed, meanwhile)

**Closed as completed by mor-n4** 2016-09-26 15:03 UTC
Labels: bug
