### ISSUE TITLE
Function kind (normal, generator, constructor) must be taken into account

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#227] opened 2016-06-20 13:23 UTC
Functions have a slot called functionKind (only in spec). This can have the value "normal", "classConstructor" or "generator". A function with "classConstructor" must not be called in a function called. Other constraints are defined in the ES6 spec.

These constraints must be extracted and we need a mechanism to define the slot in N4JS, e.g. when defining method signature. Possible solutions are pseudo types (e.g. CtorFunction, GenFunction, NormalFunction), annotations (@FunctionKind("classConstructor") ...). The relation to Function (sub or super type, completely different handling) depends on the constraints.
- Methods such has Function.call or Reflection.construct have to be adjusted.
- subtype definition of constructor has to be adjusted

**Comment by JensN4** [comment] 2016-06-30 10:13
We probably need more kinds:
- abstractConstructor
- normalNoConstructor -- to indicate special semantics in N4JS preventing normal functions to be used as constructors

**Comment by JensN4** [comment] 2016-06-30 13:10
also see remarks in https://github.numberfour.eu/NumberFour/n4js/pull/126

We should address these issues together with enhancing function metatype: only then we will be able to really fix these issues (instead of adding work-arounds)

**Comment by mor-n4** [comment] 2016-08-15 13:43
probably a duplicate of IDE-522

**Comment by mor-n4** [comment] 2018-03-14 10:01
Moved to IDE-522 (subtask IDE-2980).

Closing as DUPLICATE.

**Closed as completed by mor-n4** 2018-03-14 10:01 UTC
Labels: duplicate
