### ISSUE TITLE
Bad error location in case of missing semicolon leading to validation error.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#7] opened 2016-03-16 12:44 UTC
IDEBUG-118
 Note: please read my (Jens') comment to understand the problem. This is not a parser issue!

```
var safeEval = function safeEval(dyn){
    try{
        eval(dyn)
    } catch(e){
        console.log('error when running ' + dyn + ' : ' + e);
    }
};

(function(){
    safeEval('logFactors(-100)');
    safeEval('logFactors(-10)');
    safeEval('logFactors(-1)');
    safeEval('logFactors(0)');
    safeEval('logFactors(1)'); 
    safeEval('logFactors(10)'); 
    safeEval('logFactors(100)');
})();
```

can be parsed, where

```
var safeEval = function safeEval(dyn){
    try{
        eval(dyn)
    } catch(e){
        console.log('error when running ' + dyn + ' : ' + e);
    }
}

(function(){
    safeEval('logFactors(-100)');
    safeEval('logFactors(-10)');
    safeEval('logFactors(-1)');
    safeEval('logFactors(0)');
    safeEval('logFactors(1)'); 
    safeEval('logFactors(10)'); 
    safeEval('logFactors(100)');
})();
```

creates error marker on first function (saveEval) saying "Not a function or method: void.".

The code is erroneous: This is the result of a stripped down version of the example:

```
function f(){}()();
```

And the error message ist not that bad, because that's exactly the problem: The function f, which is called, returns void. Thus, the second call cannot succeed.

Only: The location is bad. I have set priority of this bug accordingly and change title accordingly.

**Comment by mor-n4** [comment] 2018-02-07 13:43
The behavior is correct. Even the error message makes sense when looking closely at this example.

While the entire situation is confusing for the programmer, this is caused by an intricacy of the plain Javascript syntax (the fact that the `(` two lines below wraps the function expression into a call expression). We cannot provide special error message logic for all these cases.

Also, this ticket is 4 years old and this never caused confusion during that time.

Closing as WONT FIX.

**Closed as completed by mor-n4** 2018-02-07 13:43 UTC
Labels: bug, wontfix, prio-low
