### ISSUE TITLE
IDE hangs when importing projects into working sets

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#147] opened 2016-03-23 15:45 UTC
It seems to be a deadlock. When importing a project (from local github) into the N4JSIDE, the IDE hangs. 
To reproduce:
1. import some projects (maybe from one repository) into the IDE in one working set
2. import more projects (maybe from other repository) into the IDE, using another working set
This happens in the N4JS perspective. There is no activity, just the spinning wheel.

**Comment by kittaakos** [comment] 2016-04-25 14:01
Cannot reproduce the issue any more. Most likely fixed among with other task. Closing issue.

**Closed as completed by kittaakos** 2016-04-25 14:01 UTC
