### ISSUE TITLE
Problem with "Workspace: Refresh using native hooks or polling" on OSX

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#209] opened 2016-06-09 07:41 UTC
Turning the mentioned option on causes an annoying 1-2 secs blockage of the UI thread every few seconds.

Please investigate.

I checked to have no other processes running on the workspace and/or related repository folders.

**Comment by mor-n4** [comment] 2016-06-09 14:33
this is a duplicate of IDE-2269

**Closed as completed by mor-n4** 2016-06-09 14:33 UTC
Labels: duplicate
