### ISSUE TITLE
NPE when hovering over unresolved types

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#127] opened 2016-03-16 12:57 UTC
IDEBUG-868
 Try to hover over for instance {{UnresolvedType}}. Below snippet intentionally contains zero import statements.

```
interface HasName { 
public name: string; }

class Set implements HasName { 
public items: List<IDO>; 
public size: number;
private lookupCache: Map<string, UnresolvedType>;
}
```

Exception:

```
4894733 [main] WARN  org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider  - Error in polymorphic dispatcher : null
java.lang.NullPointerException
    at org.eclipse.xtext.parser.antlr.TokenTool.getLexerRuleName(TokenTool.java:66)
    at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.getRuleName(AbstractLexerBasedConverter.java:116)
    at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.assertTokens(AbstractLexerBasedConverter.java:68)
    at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.assertTokens(AbstractLexerBasedConverter.java:58)
    at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.toString(AbstractLexerBasedConverter.java:49)
    at org.eclipse.xtext.conversion.impl.QualifiedNameValueConverter.delegateToString(QualifiedNameValueConverter.java:180)
    at org.eclipse.xtext.conversion.impl.QualifiedNameValueConverter.toString(QualifiedNameValueConverter.java:94)
    at org.eclipse.xtext.conversion.impl.QualifiedNameValueConverter.toString(QualifiedNameValueConverter.java:1)
    at org.eclipse.xtext.conversion.impl.KeywordAlternativeConverter.toString(KeywordAlternativeConverter.java:52)
    at org.eclipse.xtext.conversion.impl.KeywordAlternativeConverter.toString(KeywordAlternativeConverter.java:1)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider$DefaultProposalCreator.apply(AbstractJavaBasedContentProposalProvider.java:95)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider$DefaultProposalCreator.apply(AbstractJavaBasedContentProposalProvider.java:1)
    at eu.numberfour.n4js.ui.proposals.imports.ImportsAwareReferenceProposalCreator.lambda$0(ImportsAwareReferenceProposalCreator.java:104)
    at eu.numberfour.n4js.ui.proposals.imports.ImportsAwareReferenceProposalCreator$$Lambda$581/95783655.apply(Unknown Source)
    at eu.numberfour.n4js.ui.proposals.imports.ImportsAwareReferenceProposalCreator.lookupCrossReference(ImportsAwareReferenceProposalCreator.java:124)
    at eu.numberfour.n4js.ui.contentassist.N4JSProposalProvider.lookupCrossReference(N4JSProposalProvider.java:99)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.lookupCrossReference(AbstractJavaBasedContentProposalProvider.java:233)
    at eu.numberfour.n4js.ui.contentassist.N4JSProposalProvider.lookupCrossReference(N4JSProposalProvider.java:69)
    at eu.numberfour.n4js.ts.ui.contentassist.AbstractTypeExpressionsProposalProvider.completeParameterizedTypeRefNominal_DeclaredType(AbstractTypeExpressionsProposalProvider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:296)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.invokeMethod(AbstractJavaBasedContentProposalProvider.java:300)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.completeAssignment(AbstractJavaBasedContentProposalProvider.java:205)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractContentProposalProvider$DefaultContentAssistProcessorSwitch.caseAssignment(AbstractContentProposalProvider.java:66)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractContentProposalProvider$DefaultContentAssistProcessorSwitch.caseAssignment(AbstractContentProposalProvider.java:1)
    at org.eclipse.xtext.util.XtextSwitch.doSwitch(XtextSwitch.java:144)
    at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
    at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractContentProposalProvider$DefaultContentAssistProcessorSwitch.accept(AbstractContentProposalProvider.java:72)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractContentProposalProvider.createProposals(AbstractContentProposalProvider.java:110)
    at org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.createProposals(AbstractJavaBasedContentProposalProvider.java:275)
    at eu.numberfour.n4js.ui.utils.ImportUtil.lambda$0(ImportUtil.java:148)
    at eu.numberfour.n4js.ui.utils.ImportUtil$$Lambda$579/829000056.exec(Unknown Source)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:121)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
    at eu.numberfour.n4js.ui.utils.ImportUtil.findImportCandidates(ImportUtil.java:155)
    at eu.numberfour.n4js.ui.utils.ImportUtil.findImportCandidates(ImportUtil.java:130)
    at eu.numberfour.n4js.ui.quickfix.N4JSQuickfixProvider.addImportForUnresolvedReference(N4JSQuickfixProvider.java:221)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.xtext.ui.editor.quickfix.AbstractDeclarativeQuickfixProvider.getResolutions(AbstractDeclarativeQuickfixProvider.java:53)
    at org.eclipse.xtext.ui.editor.quickfix.AbstractDeclarativeQuickfixProvider.getResolutions(AbstractDeclarativeQuickfixProvider.java:83)
    at org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider.getResolutions(DefaultQuickfixProvider.java:244)
    at org.eclipse.xtext.ui.editor.quickfix.AbstractIssueResolutionProviderAdapter.getResolutions(AbstractIssueResolutionProviderAdapter.java:42)
    at org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor.createQuickfixes(XtextQuickAssistProcessor.java:134)
    at org.eclipse.xtext.ui.editor.quickfix.XtextQuickAssistProcessor.computeQuickAssistProposals(XtextQuickAssistProcessor.java:108)
    at org.eclipse.xtext.ui.editor.hover.AnnotationWithQuickFixesHover$CompletionProposalRunnable.run(AnnotationWithQuickFixesHover.java:603)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at eu.numberfour.n4js.product.N4Application.start(N4Application.java:141)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

```

**Comment by kittaakos** [comment] 2016-04-05 10:30
Cannot reproduce any more. Closing issue.

**Closed as completed by kittaakos** 2016-04-05 10:30 UTC
Labels: bug
