### ISSUE TITLE
Invalid warning for `@Internal` field in spec-style ctor

### ISSUE THREAD

**Issue by dbo** [NumberFour/n4js#207] opened 2016-06-02 12:23 UTC
##### A.n4js.xt

```
class C {
    @Internal public foo: int;

    constructor(@Spec spec: ~i~this) {}
}

// XPECT FIXME nowarnings --> "foo is not used in constructor."
new C({ foo: 5 })
```

**Comment by mor-n4** [comment] 2016-06-29 08:00
duplicate of #214

**Closed as completed** 2016-06-29 08:00 UTC
Labels: duplicate
