### ISSUE TITLE
Better error message for instanceof used with primitive types

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#21] opened 2016-03-16 12:44 UTC
IDEBUG-292
 When instanceof is used with a primitive type on the right-hand side, the error message should be more explanatory. Currently it is "cannot type IdentifierRef string." for string, for example.

{panel:title=Generated bug report|borderStyle=dashed|borderColor=#ccc|titleBGColor=#8192A6|bgColor=#dedee0}

```
var string s = "s";
// XPECT FIXME errors --> "primitive types are not allowed on the right-hand side of the instanceof operator" at "string" 
s instanceof string;
```

{panel}

**Comment by lbeurerkellner** [comment] 2017-06-23 16:01
Updated snippet would be:

```
var s : string = "s";
// XPECT FIXME errors --> "primitive types are not allowed on the right-hand side of the instanceof operator" at "string" 
s instanceof int;
```

Also, the error message is different now: `Couldn't resolve reference to IdentifiableElement 'int'.`

This is because the right-hand-side of the relational instanceof expression is parsed as an IdentifierRef. Therefore, the current implementation of N4JSScopeProvider provides us with an Identifier Scope which doesn't contain primitive types anymore. (See https://github.com/NumberFour/n4js/issues/280) 
Non-primitive types aren't concerned by this, as they can also appear as Identifiers. 

To fix this we could make use of the newly introduced `N4JSScopingDiagnostician` to handle the scoping failure more gracefully.

**Comment by mor-n4** [comment] 2017-07-05 09:34
this was merged to master, but then an SWTBot test failed. Did set test class `AssignWorkingSetsSwtBotTest` on ignore.

TODO: please fix & re-enable test `AssignWorkingSetsSwtBotTest`

**Comment by lbeurerkellner** [comment] 2017-07-11 10:10
Since the build you had linked me in the email is gone, I am currently trying to reproduce the test failure. Unfortunately, I had no luck so far.

**Comment by yoosiba** [comment] 2017-07-12 07:20
If it works, it works. Once SWTBot flakiness activates again, then we can deal with it.

**Comment by yoosiba** [comment] 2017-07-12 07:20
if merged, close.

**Comment by mor-n4** [comment] 2017-07-12 09:39
The test is currently on ignore. If you want to wait for the next random failure, please re-enable the test and then close this ticket.

**Comment by lbeurerkellner** [comment] 2017-07-18 07:30
Test is re-enabled on master.

**Closed as completed by lbeurerkellner** 2017-07-18 07:30 UTC
Labels: enhancement, prio-low
