### ISSUE TITLE
Add OS X Eclipse Launcher to N4IDE

### ISSUE THREAD

**Issue by JensN4** [NumberFour/n4js#353] opened 2017-02-22 16:01 UTC
Please add the 
         OS X Eclipse Launcher Utility
to the N4IDE.

Update site: https://resheim.net/p2/eclipse-launcher/
Project home: https://github.com/turesheim/eclipse-launcher
License: EPL (please add that to the spec as 3rd party tools).

**Comment by lbeurerkellner** [comment] 2017-04-07 16:03
~~There seems to be an issue with having an Oomph Targlet and a platform-specific dependency. I posted on the Eclipse Oomph forum here: https://www.eclipse.org/forums/index.php/t/1085468/~~

~~The problem is, that on non-MacOS platforms, oomph will remove the update site from the generated target definition, since there is no dependency on these platforms. This is unfortunate as the generated definition is checked into git. This means that every time a non-MacOS developer performs the setup task, the generated .target file will be changed and one has to be very careful not to commit this unintended change.~~
~~Also there will be a validation warning, as the feature identifier can't be resolved in this case.~~

See latest comment.

**Comment by lbeurerkellner** [comment] 2017-05-02 08:54
~~I could resolve the issues with the Oomph setup by using the extraUnits detail of the TargetDefinitionGenerator. (See GH-353-extraUnits)
Due to the setup redirection issues with the current renaming going on, I would prefer merging this after the renaming was done.~~

See latest comment.

**Comment by lbeurerkellner** [comment] 2017-06-02 15:08
After filing a bug with the oomph project (https://bugs.eclipse.org/bugs/show_bug.cgi?id=516040), I managed to solve this the proper way. (See GH-353-proper) 

It turned out the includeAllPlatforms option has to be specified on two levels. Once as an attribute on the `<targlet>` element and once as an `<detail>` of type annotation for the generated target definition. 

Unfortunately, I still haven't found any documentation on this and for me the bug report was the only way of learning about it.

**Closed as completed** 2018-03-12 08:18 UTC
Labels: enhancement
