### ISSUE TITLE
Type visibility computation in case of test-projects broken.

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#64] opened 2016-03-16 12:52 UTC
IDEBUG-640
 Former refactorings of  /eu.numberfour.ide.n4js/src/eu/numberfour/ide/n4js/scoping/accessModifiers/TypeVisibilityChecker.java

silently broke the former logic, basically ignoring important FALLTHROUGH semantics in a switch-statement.

This has to be reviewed.

Correct old state: c31eaaed575f27101d5f941b523022e6079728df
Broken refactoring: c649330e90d45d4f013bf44dbc5742888814ce4c

**Comment by mor-n4** [comment] 2016-09-22 12:44
closing this as duplicate of IDE-2347
In particular, note my comment below that task where I link here:
https://jira.numberfour.eu/browse/IDE-2347?focusedCommentId=46291&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46291

**Closed as completed by mor-n4** 2016-09-22 12:44 UTC
Labels: bug, duplicate
