### ISSUE TITLE
Dropping super initializer code in transpiled output when super type is plain JS Object

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#85] opened 2016-03-16 12:56 UTC
IDEBUG-715
 If you have a look at the transpiled output for the following class:

```
export public class HTTPError extends Error {
    public constructor(number status, string? statusText) {
        super("[" + status + "] " + (statusText == null ? "error" : statusText));
        this.status = status;
        this.statusText = statusText;
    }

    @Final public number status;
    @Final public string? statusText;
}
```

you'll notice that the super-initializer of the message has been completely dropped:

```
 HTTPError = function HTTPError(status,statusText) {
    var er = new Error();
    this.message = er.message;
    this.name = this.constructor.n4type.name;
    Object.defineProperty(this, 'stack', { get: function() { return er.stack; } });
this.status = undefined;
    this.statusText = undefined;

        this.status = status;
        this.statusText = statusText;
    };
```

issue above is happening only when super class is JS built in object.
For plain N4JS spertypes compiled code seems fine:

```
export public class Error{

        constructor(f){}
} 

export public class HTTPError extends Error {
    public constructor(number status, string? statusText) {
        super("[" + status + "] " + (statusText == null ? "error" : statusText));
        this.status = status;
        this.statusText = statusText;
    }

    @Final public number status;
    @Final public string? statusText;
}
```

produces

```
var Error, HTTPError;
Error = function Error(f){};
$n4Export('Error', Error);
HTTPError = function HTTPError(status,statusText){
                                 Error.prototype.constructor.call(this, (('[' + status) + '] ') + ((statusText == null) ? 'error' : statusText));
                                this.status = undefined;
                                    this.statusText = undefined;
                                this.status = status;
                                this.statusText = statusText;
                              }                                                                                                                  ;
$n4Export('HTTPError', HTTPError);
```

**Comment by JensN4** [comment] 2016-08-12 14:58
also see IDE-2286

**Comment by JensN4** [comment] 2016-09-02 13:54
also re-check with ES6 semantics!

**Comment by mor-n4** [comment] 2016-09-21 09:21
all examples from the issue description transpile as intended (and as requested in the issue description), so this has been fixed in the mean time (issue is from Nov 2015).

closing as "fixed"

**Closed as completed by mor-n4** 2016-09-21 09:21 UTC
Labels: bug
