### ISSUE TITLE
Possibly missing validation for redeclared identifiers when mixing var and let

### ISSUE THREAD

**Issue by kduske-n4** [NumberFour/n4js#269] opened 2016-09-22 10:22 UTC
The following N4JS snippet

```
function x() {
    let b = false;
    var b = true;
}

x();
```

when run in Node.js produces the following error output:

```
SyntaxError: Identifier 'b' has already been declared
    Evaluating /Users/kristian.duske/Oomph/Secondary/ws/Runtime-N4JS-N4/AccessControl/src-gen/es/AccessControl/a/A.js
    Error loading AccessControl/a/A
```

It looks as if we are missing a validation here.

Note that the problem does not depend on the order of the declarations:

```
function x() {
    var b = true;
    let b = false;
}

x();
```

produces the same error.

**Comment by mor-n4** [comment] 2016-09-23 05:46
duplicate of IDE-2220 "As a developer I want "var" being validated as in ES5/ES6 and have the relation var vs. let/const behave as in ES6"

**Closed as completed** 2016-09-23 05:46 UTC
Labels: duplicate
