### ISSUE TITLE
ISE when canceling auto-build job

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#63] opened 2016-03-16 12:52 UTC
IDEBUG-636
 Although the job is not canceled at all I can see this in the log:

```
java.lang.IllegalStateException: cache miss: no actual type in cache for AST node: eu.numberfour.ide.n4js.n4JS.impl.IdentifierRefImpl@523ec89d in resource: platform:/resource/runtime.n4/src/n4js/runtime/n4/N4Injector.n4js
    at eu.numberfour.ide.n4js.postprocessing.TypingCacheHelper$TypingCache.get(TypingCacheHelper.java:72)
    at eu.numberfour.ide.n4js.postprocessing.TypeProcessor.xsemantics_type(TypeProcessor.java:274)
    at eu.numberfour.ide.n4js.typesystem.CustomTypeSystem.typeInternal(CustomTypeSystem.java:165)
    at eu.numberfour.ide.n4js.xsemantics.N4JSTypeSystem.type(N4JSTypeSystem.java:572)
    at eu.numberfour.ide.n4js.xsemantics.N4JSTypeSystem.type(N4JSTypeSystem.java:567)
    at eu.numberfour.ide.n4js.typeinference.N4JSTypeInferencer.tau(N4JSTypeInferencer.java:148)
    at eu.numberfour.ide.n4js.typeinference.N4JSTypeInferencer.tau(N4JSTypeInferencer.java:93)
    at eu.numberfour.ide.n4js.typeinference.N4JSTypeInferencer.tau(N4JSTypeInferencer.java:85)
    at eu.numberfour.ide.n4js.scoping.N4JSScopeProvider.scope_PropertyAccessExpression_property(N4JSScopeProvider.java:524)
    at eu.numberfour.ide.n4js.scoping.N4JSScopeProvider.getScope(N4JSScopeProvider.java:204)
    at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
    at eu.numberfour.ide.n4js.resource.ErrorAwareLinkingService.getLinkedObjects(ErrorAwareLinkingService.java:53)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:250)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:225)
    at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:136)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1473)
    at eu.numberfour.ide.n4js.n4JS.impl.ParameterizedPropertyAccessExpressionImpl.getProperty(ParameterizedPropertyAccessExpressionImpl.java:161)
    at eu.numberfour.ide.n4js.n4JS.impl.ParameterizedPropertyAccessExpressionImpl.eGet(ParameterizedPropertyAccessExpressionImpl.java:231)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
    at eu.numberfour.ide.n4js.resource.N4JSCrossReferenceComputer.handleReference(N4JSCrossReferenceComputer.java:84)
    at eu.numberfour.ide.n4js.resource.N4JSCrossReferenceComputer.computeCrossRefs(N4JSCrossReferenceComputer.java:73)
    at eu.numberfour.ide.n4js.resource.N4JSCrossReferenceComputer.computeCrossRefs(N4JSCrossReferenceComputer.java:59)
    at eu.numberfour.ide.n4js.resource.N4JSResourceDescription.getImportedNames(N4JSResourceDescription.java:82)
    at org.eclipse.xtext.builder.builderState.BuilderStateUtil.copyImportedNames(BuilderStateUtil.java:40)
    at org.eclipse.xtext.builder.builderState.BuilderStateUtil.create(BuilderStateUtil.java:35)
    at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:236)
    at eu.numberfour.ide.n4js.ui.building.N4JSGenerateImmediatelyBuilderState.doUpdate(N4JSGenerateImmediatelyBuilderState.java:85)
    at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:115)
    at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:248)
    at eu.numberfour.ide.n4js.ui.building.N4JSBuildTypeTrackingBuilder.doBuild(N4JSBuildTypeTrackingBuilder.java:47)
    at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:280)
    at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mor-n4** [comment] 2016-07-06 14:34
considering the above stack trace, this should be fixed by #225 (and also #228);
since the issue description does not state exactly how to reproduce the problem, closing this now

**Closed as completed by mor-n4** 2016-07-06 14:34 UTC
Labels: bug
