### ISSUE TITLE
Use-site structural typing not working with type variables

### ISSUE THREAD

**Issue by NumberFourAG** [NumberFour/n4js#12] opened 2016-03-16 12:44 UTC
IDEBUG-225
 In the following example, the use-site structural typing of type variable T will be ignored:

```
class A {
    public string name;
}
class B {
    public string name;
}



class C<T> {
    public ~T field; // note: T is use-site structural!

    // TODO when it's working, also test with methods and accessors!
}

var ~C<A> ca_struct;
var C<B> cb;

// XPECT FIXME type of 'cb.field' --> ~B
cb.field; // type inferred to B instead of ~B

// XPECT FIXME noerrors -->
ca_struct = cb; // but getting: "C<B> is not a structural subtype of ~C<A>: field failed: B is not a subtype of A."

// XPECT FIXME noerrors -->
ca_struct.field = {name:"x"}; // but getting: "~Object with { string name; } is not a subtype of A."

var ~B test = ca_struct.field  // <-- works, but for the wrong reasons! type inferred to A instead of ~A
```

The problem is that the typing strategy of the type variable is not copied to the type argument upon substitution. However, simple copying is not possible because:
- [x] 1) sometimes the type argument is structurally typed and not the type variable, this must not get lost due to plain copying of the typing strategy flag from variable to argument (easy to solve).
- [ ] 2) what if the type variable uses structural field typing, the type argument ordinary structural typing? (and other conflicts)
- [x] 3) what if the type argument is not a subtype of StructuralTypeRef? (then there's no place to store the TypingStrategy; type argument has to be converted into a StructuralTypeRef)
- [ ] 4) what if the type argument is a subtype of TypeRef that does not support structural typing (e.g. union types)?
- [x] 5) ...
- [ ]  6)

**Comment by mmews-n4** [comment] 2016-08-24 09:25
A similar situation occurred in one of the XPECT test cases: When using object literals to create an structural type object, this new object might have nested fields. In case the nested field is also of structural type, it should also be possible to assign an object literal to it. This is not possible in the situation below.

```
interface A {    public i : int;   }
interface I<T> {    public x : ~T;    }

class     C2   {   
    // ATTENTION return value must be ~I, as well
    // XPECT FIXME noerrors -->
    public f2b () : ~I<A> { return {x: {i: 3} };  }
}
```

Note: search for GH-250 in matrix tests.

**Comment by mmews-n4** [comment] 2016-08-24 10:20
5.1) Using `with` can create collisions. Consider the following example:

```
class A {
    public prop : number;
}
var a : ~A with {prop : string};
a.prop; // type: string
var as : ~A;
as = a; // ~A with{...} <: ~A
as.prop; // type number
```

In the example, (1) a collision occurs, (2) no warning is shown, and (3) the subtype relation between the types of `a` and `as` is valid. These three elements contradict each other, and thus, we need some changes.

5.2) Using `with` to add properties to a structural type creates collisions. Consider the following example:

```
class A {
    public prop : number;
}
interface I<T> {
    field : ~T with {prop : string}; 
}
var v : I<A>; 
```

In the example, the declaration of `v` creates an collision caused by the property `prop`, since this property has two different types.

**Comment by mmews-n4** [comment] 2016-08-24 10:20
**Results of discussion**

Points 1) and 3) are solved.

**Point 2)**
Consider the following example:

```
class A {}
interface I<T> {
    field : ~T; // ST1
}
var v : I<~A>; // ST2
```

In the example, there are two use-site structural types: ST1 and ST2. Here, both of them are of type ~{}. But other combinations are possible like (example 2:) `ST1 = ~r~{}` and `ST2 = ~~A`. The question regarding the resulting type for the property `field` is answered using the concatenation of the structural type parameters. In example 2, the resulting type would be `~r~{}`, since the concatenation is: `~r~{~~A}`. 
To solve point 2), a complete table of combinations has to created and missing structural types resulting from these combinations will be added. In the implementation, the resulting type is saved rather than a list of the structural type parameters.

**Point 4)**
Consider the following example:

```
class A {}
class B {}
var v1 = union{~A, ~B};
var v2 = ~union{A,B};
var v3 = I<union{A,B}>;
```

In the example, the declaration of v1 is valid, whereas - as of now - the declarations of v2 and v3 are not, since union types currently can not be structural. So solve point 2), we will allow composed types to be structural. Furthermore, also function types (https://github.com/NumberFour/n4js/issues/249) and classifier types will be allowed to be structural.

**Point 5.1)** The general question is, if structural types using `with`should have a subtype relation, or if they should be completely independent from each other. The constraint for our decision was: In case we can detect all collisions, we want subtyping. Since we are optimistic to detect all collisions, the resulting change is: Enhance the validator to detect collisions.

**Point 5.2)** To detect this collision in general, every declaration has to be checked against the declared type. Since we regard this check as expensive, the use of `with` on type variables will be forbidden.

**Comment by mmews-n4** [comment] 2016-08-24 16:31
**Point 2)** 

**Question:** _What is the resulting subtype relation, when by means of type variables nested structural typing rules are used (at several use sites)?_

Regarding the following example, the use sites are ST1 and ST2 and the type of v is ~i~{~r~A}:

```
class A {
    public df : string;
}
interface I<T> {
    field : ~i~T; // ST1
}
var v : I<~r~A>; // ST2
```

**Answer:** _The subtype relations are computed on the fly be concatenating all the nested strategies._

**Comment by mmews-n4** [comment] 2016-09-13 06:27
As mentioned above, this issue was broken into five subtasks. Subtask 1) was already solved before committing to this issue. Subtasks 3) and 5) are solved and merged by the pull request https://github.numberfour.eu/NumberFour/n4js/pull/189. 

However, this pull request does not close GH-12. When the work on the subtasks 2) and 4) of GH-12 is continued, the subtask 3) might have to be revisited.

**Comment by mor-n4** [comment] 2016-09-14 09:40
6) reconsider combination with dynamic types, for example:

``` javascript
class A {}

class G<T> {
    field: ~T;
}

let g2: G<A+>;
// XPECT type of 'g2.field' --> ???
g2.field;
```

Do we want to see a type like `+~A` for `g2.field` above?

**Comment by mor-n4** [comment] 2018-02-07 14:41
Moved remaining open issue to a follow-up user story: IDE-2965.

Therefore closing this now.

**Closed as completed by mor-n4** 2018-02-07 14:41 UTC
Labels: bug
